### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by ankane** [ankane/informers#1]
Tasks

Task | Model | Tokenizer | Blocked On
--- | --- | --- | ---
Translation | `t5-base` | T5 | export (`Missing Input: decoder_input_ids`)
Summarization | `sshleifer/distilbart-cnn-12-6` | RoBERTa | export
Summarization | `google/pegasus-xsum` | Pegasus | export
Summarization | `facebook/bart-large-cnn` | RoBERTa | export
Zero-shot classification | `facebook/bart-large-mnli` | RoBERTa | export
Conversational | `microsoft/DialoGPT-medium` | GPT2 | export

Ideas

- [ ] Download models automatically
- [ ] Use zip or tar for models
- [ ] Support longer text for question answering
- [ ] Support `do_sample` and `num_return_sequences` for text generation
- [ ] Use `starts` and `ends` instead of `start` and `end`
- [ ] Add `tokenizer` option for models (to support more ONNX models per task)

**Comment by MatheusRich** [comment]
Hi @ankane, first of all, thanks for your AMAZING work for the Ruby community! Secondly, is there any way to use Informers in other languages already?

**Comment by ankane** [comment]
Hey @MatheusRich, thanks! Can you explain more about the 2nd part?

**Comment by MatheusRich** [comment]
I mean using it for Portuguese, for example.

**Comment by ankane** [comment]
I haven't tried it with other languages, but if there are [models](https://huggingface.co/models) for the supported tasks, it should be possible (if a model uses a different tokenizer, may need to add an option for it). If you try it and get stuck, feel free to open an issue with a minimal script with what you're trying to do.

**Comment by ilyazub** [comment]
Hey @ankane, thanks for your work!

I'd like to add a GitHub workflow for exporting models (https://github.com/ankane/informers/blob/master/tools/export.md) and adding it to GitHub releases. This would speed up on-boarding for the first-time users.

What do you think?

**Comment by ankane** [comment]
@ilyazub Just released 1.0.0, which downloads models from Hugging Face.
