### ISSUE TITLE
Supporting sparse and late-interaction embedding models

### ISSUE THREAD

**Issue by codenamev** [ankane/informers#13]
I am looking to add some support for a couple models to parallel some features we need from the [qdrant's fastembed library](https://github.com/qdrant/fastembed).  Namely: [Qdrant/bm25](https://huggingface.co/Qdrant/bm25) and [colbert-ir/colbertv2.0](https://huggingface.co/colbert-ir/colbertv2.0/blob/main/README.md)

Both of these behave slightly differently than the EmbeddingPipeline, however I'd like to follow your guidance on whether or not it should implement a new pipeline for these.

## BM25
Qdrant uses this within fastembed as a sparse embedding.  I would love your insight into how this might fit into the informers architecture as there is no traditional modelfile and is more of just an algorithm.

## ColBERT v2
Late-interaction embedding architecture requires some [pre-procsessing](https://github.com/qdrant/fastembed/blob/main/fastembed/late_interaction/colbert.py#L70) and [post-processing](https://github.com/qdrant/fastembed/blob/main/fastembed/late_interaction/colbert.py#L48) of the input/output.  Do you have any design preference on where this lives?

**Comment by ankane** [comment]
Hi @codenamev, I'm not sure either of these are a good fit for Informers right now. `Qdrant/bm25` doesn't have an ONNX model, and `colbert-ir/colbertv2.0` doesn't have any docs for how to use the ONNX model and isn't included in Transformers.js. I think it'd be better if someone created a port of `fastembed` for these.
