### ISSUE TITLE
Bug can't download model

### ISSUE THREAD

**Issue by buithehien1991** [ankane/informers#14]
Dear @ankane 

When I try run first command, error happen: 

![image](https://github.com/user-attachments/assets/36dac618-624b-4934-b9e4-57e640dd225b)

When I debug, width = 0.

My env is Mac OS Sonoma. Ruby 3.3. Rails 7.2

**Comment by buithehien1991** [comment]
When I replace by Transformer.rb. New error happen

```
NameError: undefined local variable or method `e' for module Transformers::HfHub
from /Users/hienbt/.rvm/gems/ruby-3.3.0/gems/transformers-rb-0.1.5/lib/transformers/hf_hub/utils/_errors.rb:89:in `rescue in hf_raise_for_status'
Caused by Net::HTTPClientException: 416 "Range Not Satisfiable"
from /Users/hienbt/.rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/net/http/response.rb:277:in `error!'
```

**Comment by ankane** [comment]
Hi @buithehien1991, thanks for reporting! Pushed a fix for Informers in the commit above.

**Comment by ankane** [comment]
Fixed the Transformers error in https://github.com/ankane/transformers-ruby/commit/333bd872579d9a2e820fc8cf1b806065015b4684.

**Comment by buithehien1991** [comment]
@ankane I tested and it worked perfectly. Please create new tag version. Thank you so much
