### ISSUE TITLE
Unable to generate NER model

### ISSUE THREAD

**Issue by sivagollapalli** [ankane/informers#5]
Getting error as follows while doing `pip3 install`
<img width="1159" alt="Screenshot 2024-01-09 at 2 57 02 PM" src="https://github.com/ankane/informers/assets/280199/e9d67684-14e9-44ba-a0ab-f01122c4db73">
Looks like torch==1.7.1 is no more exists. So I upgraded versions as follows

```
torch==2.1.2
transformers==4.36.2
onnx
onnxruntime
```

After that I am able to complete `pip3 install -r requirements.txt` but I am unable to complete `python3 generate_ner.py` step.  Getting following error: 

<img width="1302" alt="Screenshot 2024-01-09 at 3 00 51 PM" src="https://github.com/ankane/informers/assets/280199/a716c35e-8a50-4f45-bddb-8383db00bb09">

**Comment by ankane** [comment]
Hi @sivagollapalli, thanks for reporting! Updated the scripts to use Optimum in the commit above.
