### ISSUE TITLE
Supporting Multilingual text embedding using paraphrase-multilingual-MiniLM-L12-v2

### ISSUE THREAD

**Issue by wittawasw** [ankane/informers#8]
It'd be nice if the text-embedding support at least 1 multilingual model.

In [sentence-transformers](https://huggingface.co/sentence-transformers) default page, they kind of recommend us to use [paraphrase-multilingual-MiniLM-L12-v2](https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2) as one can see from their example.

```python
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('paraphrase-MiniLM-L6-v2')

# Sentences we want to encode. Example:
sentence = ['This framework generates embeddings for each input sentence']

# Sentences are encoded by calling model.encode()
embedding = model.encode(sentence)
``` 

We can still keep [sentence-transformers/all-MiniLM-L6-v2](https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2) as a default text embedding but we should have an option to use th multilingual one.

Right now, I tried replacing the model name in current API and it return this error

```ruby
model = Informers.pipeline("embedding", "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2")
#  Unknown tokenizer class "PreTrainedTokenizer", attempting to construct from base class.
#  /home/username/.rbenv/versions/3.3.5/lib/ruby/3.3.0/open-uri.rb:376:in `open_http': 404 Not Found (OpenURI::HTTPError)
```

Can you give some direction as to how should I implement and include it in the this gem ?

**Comment by wittawasw** [comment]
I see now that it's just the matter of the model on Huggingface doesn't have ONNX model for download at the moment.
https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/discussions/11

And I just looked up the `transformers-rb`, too. So, it's probably better to keep the same API here to support ONNX model only since I can have a workaround already.

**Comment by ankane** [comment]
Hi @wittawasw, there is ONNX version of the model at [Xenova/paraphrase-multilingual-MiniLM-L12-v2](https://huggingface.co/Xenova/paraphrase-multilingual-MiniLM-L12-v2), but it currently errors when loading the tokenizer (due to https://github.com/huggingface/tokenizers/issues/1627).

**Comment by ankane** [comment]
Just fyi, ONNX models were added last week.

https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/tree/main/onnx
