### ISSUE TITLE
Invalid output name: sentence_embedding

### ISSUE THREAD

**Issue by mkchoi212** [ankane/informers#9]
Hey @ankane, thanks for your wonderful work on transformers.rb and neighbors :) Been a happy user of neighbors especially!

Trying to get the basic example working with the provided sample code in the README

```ruby
sentences = ["This is an example sentence", "Each sentence is converted"]

model = Informers.pipeline("embedding", "sentence-transformers/all-MiniLM-L6-v2")
embeddings = model.(sentences)
```

but currently getting the following error

```
OnnxRuntime::Error: Invalid output name: sentence_embedding
from /Users/mike/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/onnxruntime-0.9.2-arm64-darwin/lib/onnxruntime/inference_session.rb:472:in `check_status'
```

**Comment by mkchoi212** [comment]
Seems like 
```ruby
model = Informers.pipeline("embedding", "Xenova/all-MiniLM-L6-v2", quantized: true)
```

works though. For reference, I'm on an M1 Macbook

**Comment by ankane** [comment]
Hi @mkchoi212, thanks for reporting. Looks like the model was updated [a few days ago](https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/commit/bc57282bc374d33e0d6c4de27f12dc1c2a87f37a) to have different outputs. Fixed in the commit above.

**Comment by mkchoi212** [comment]
ur amazing thank you!

**Comment by ankane** [comment]
No problem, just pushed version 1.1.1.
